apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: test-deploy
  name: test-server-1-default
  labels:
    part-of: test-deploy
    component: backend-server
    instance: test-server-1
    version: 1.0.0
    managed-by: kubectl
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-server-1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120