apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test-deploy
  name: test-server-1-files
  labels:
    part-of: test-deploy
    component: backend-server
    name: test-server
    instance: test-server-1
    version: 1.0.0
    managed-by: kubectl

spec:
  resources:
    requests:
      storage: 1G

  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      part-of: test-deploy
      component: backend-server
      name: test-server
      instance: test-server-1