apiVersion: v1
kind: Secret
metadata:
  namespace: test-deploy
  name: api-tester-1-secret
  labels:
    part-of: test-deploy
    component: backend-server
    name: test-server
    instance: test-server-1
    version: 1.0.0
    managed-by: kubectl
stringData:
  secret-info.yaml: |
    key_string: "value_string"